---
- name: Install python packages
  apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
      - python3-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
  become: yes
  environment:
    http_proxy: http://proxy.elhub.cloud:3128
    https_proxy: http://proxy.elhub.cloud:3128
    no_proxy: "localhost,.elhub.cloud,169.254.169.254,.oraclecloud.com"

- name: Install pip python packages
  pip:
    name:
      - python-ldap
      - epdb
      - oci
    extra_args: --user
  environment:
    DISPLAY: ''  # Fix to resolve extremely slow installs on WSL2 (see https://github.com/microsoft/WSL/issues/6643)
