---
# version of node to install, defaults to 'latest'
node_version: 'v20.10.0'

nvm_version: '0.39.4'

# Install path for nvm (defaults to $HOME/.nvm)
nvm_install_path: "{{ ansible_env.HOME }}/.nvm"
