---
- name: Ensure vault lib dir
  file:
    path: "{{ vault_dir }}"
    state: directory

- name: Get vault binaries
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    remote_src: yes
    dest: "{{ vault_dir }}"
    creates: "{{ vault_dir }}/vault"

- name: Symlink to .local/bin
  file:
    src: "{{ vault_dir }}/vault"
    dest: "{{ ansible_env.HOME }}/.local/bin/vault"
    state: link

- name: Install autocomplete
  command: "{{ ansible_env.HOME }}/.local/bin/vault -autocomplete-install"
  register: _vault_autocomplete
  failed_when: _vault_autocomplete.rc != 0 and 'already installed' not in _vault_autocomplete.stderr
  changed_when: _vault_autocomplete.rc == 0

- name: Ensure 'hvac' for the ansible lookup plugin
  pip:
    name: hvac
    executable: pip3

- include_tasks: vault_env.yml
