---
- name: ensure nvm is installed
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ nvm_install_path }}/nvm.sh"

- name: install node
  shell: |
    . {{ nvm_install_path }}/nvm.sh
    nvm install {{ node_version }}
  args:
    executable: /bin/bash
  register: node_version_response
  changed_when: "'already installed' not in node_version_response.stderr"
